spring:
  # Default profile - cloud-ready configuration
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  # PostgreSQL Configuration with fallback
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    hikari:
      initialization-fail-timeout: 0
      connection-timeout: 5000
      maximum-pool-size: 2
      minimum-idle: 0

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.H2Dialect}
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true
    open-in-view: false

  # MongoDB Configuration - conditional
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:}
      auto-index-creation: false

  # Email Configuration - resilient
  mail:
    host: ${EMAIL_HOST:localhost}
    port: ${EMAIL_PORT:1025}
    username: ${EMAIL_USERNAME:test}
    password: ${EMAIL_PASSWORD:test}
    test-connection: false
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  # Security Configuration - resilient
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:}

# Server Configuration
server:
  port: ${PORT:8080}
  shutdown: graceful

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
  health:
    defaults:
      enabled: false
