spring:
  # PostgreSQL Configuration (for User entity)
  datasource:
    url: jdbc:postgresql://localhost:5432/pgsql
    username: postgres
    password: 1605
    driver-class-name: org.postgresql.Driver

  # JPA Configuration for PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # MongoDB Configuration (for dynamic tables)
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring-app
      # username: your_mongo_username  # uncomment if auth enabled
      # password: your_mongo_password  # uncomment if auth enabled

keycloak:
  server-url: http://localhost:9090
  realm: endora_api
  admin:
    client-id: admin-cli
    client-secret: eUmu5xJnDDiphTPiy7BAKhC3xNREGZCe

server:
  port: 8080

# Make MongoDB connection optional
management:
  health:
    mongo:
      enabled: false