spring:
  # PostgreSQL Configuration (for User entity)
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/endora_db
    username: tochratana
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # MongoDB Configuration (for dynamic tables)
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Endora
      # username: your_mongo_username  # uncomment if auth enabled
      # password: your_mongo_password  # uncomment if auth enabled

  # Keycloak Configuration
  security:
    oauth2:
      resource server:  # Fixed: removed space and corrected case
        jwt:
          issuer-uri: https://endora-oauth2.istad.co/realms/endora_api

  # Virtual Threads
  threads:
    virtual:
      enabled: true

  # Mail Configuration - Fixed: moved to correct level and updated with real SMTP settings
  mail:
    host: smtp.gmail.com  # Example for Gmail - replace with your SMTP provider
    port: 587
    username: your-email@gmail.com  # Replace with your actual email
    password: your-app-password     # Replace with your app password (not regular password)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000

# Keycloak Configuration
keycloak:
  server-url: https://endora-oauth2.istad.co/
  realm: endora_api
  client-id: endora_api  # This should be your actual client ID for user authentication
  client-secret: your-actual-client-secret  # Replace with your actual client secret
  admin:
    client-id: admin-cli
    client-secret: b2L6hrMg76JLk4GSLd8CGMPRJNnAOko2

server:
  port: 8080

app:
  otp:
    expiry-minutes: 5
    max-attempts: 3

# Make MongoDB connection optional
management:
  health:
    mongo:
      enabled: false

# Logging
logging:
  level:
    com.tochratana.api: DEBUG
    org.keycloak: DEBUG
    org.springframework.mail: DEBUG  # Add this to debug email issues